release32 = ["-DCMAKE_BUILD_TYPE=Release", "-DPLUGIN_CONFLICT_LEARNING_ENABLED:BOOL=1"]
debug32 = ["-DCMAKE_BUILD_TYPE=Debug"]
release32nolp = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO"]
debug32nolp = ["-DCMAKE_BUILD_TYPE=Debug", "-DUSE_LP=NO"]
release64 = ["-DCMAKE_BUILD_TYPE=Release", "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DPLUGIN_CONFLICT_LEARNING_ENABLED:BOOL=1"]
debug64 = ["-DCMAKE_BUILD_TYPE=Debug", "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DPLUGIN_CONFLICT_LEARNING_ENABLED:BOOL=1"]
release64nolp = ["-DCMAKE_BUILD_TYPE=Release", "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DUSE_LP=NO"]
debug64nolp = ["-DCMAKE_BUILD_TYPE=Debug",   "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DUSE_LP=NO"]
minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_PLUGINS_BY_DEFAULT=YES"]

release32dynamic = ["-DCMAKE_BUILD_TYPE=Release", "-DFORCE_DYNAMIC_BUILD=YES"]
debug32dynamic = ["-DCMAKE_BUILD_TYPE=Debug", "-DFORCE_DYNAMIC_BUILD=YES"]
release64dynamic = ["-DCMAKE_BUILD_TYPE=Release", "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DFORCE_DYNAMIC_BUILD=YES"]
debug64dynamic = ["-DCMAKE_BUILD_TYPE=Debug",   "-DALLOW_64_BIT=True", "-DCMAKE_CXX_FLAGS='-m64'", "-DFORCE_DYNAMIC_BUILD=YES"]

release32minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DUSE_LP=NO", "-DPLUGIN_POTENTIALS_ENABLED=NO", "-DPLUGIN_OPERATOR_COUNTING_ENABLED=NO", "-DPLUGIN_LANDMARKS_ENABLED=NO", "-DPLUGIN_MAS_HEURISTIC_ENABLED=NO", "-DPLUGIN_PDBS_ENABLED=NO", "-DPLUGIN_CEGAR_ENABLED=NO"]
debug32minimal   = ["-DCMAKE_BUILD_TYPE=Debug",   "-DUSE_LP=NO", "-DPLUGIN_POTENTIALS_ENABLED=NO", "-DPLUGIN_OPERATOR_COUNTING_ENABLED=NO", "-DPLUGIN_LANDMARKS_ENABLED=NO", "-DPLUGIN_MAS_HEURISTIC_ENABLED=NO", "-DPLUGIN_PDBS_ENABLED=NO", "-DPLUGIN_CEGAR_ENABLED=NO"]
release64minimal = ["-DCMAKE_BUILD_TYPE=Release", "-DALLOW_64_BIT=True", "-DUSE_LP=NO", "-DPLUGIN_POTENTIALS_ENABLED=NO", "-DPLUGIN_OPERATOR_COUNTING_ENABLED=NO", "-DPLUGIN_LANDMARKS_ENABLED=NO", "-DPLUGIN_MAS_HEURISTIC_ENABLED=NO", "-DPLUGIN_PDBS_ENABLED=NO", "-DPLUGIN_CEGAR_ENABLED=NO"]
debug64minimal   = ["-DCMAKE_BUILD_TYPE=Debug",   "-DALLOW_64_BIT=True", "-DUSE_LP=NO", "-DPLUGIN_POTENTIALS_ENABLED=NO", "-DPLUGIN_OPERATOR_COUNTING_ENABLED=NO", "-DPLUGIN_LANDMARKS_ENABLED=NO", "-DPLUGIN_MAS_HEURISTIC_ENABLED=NO", "-DPLUGIN_PDBS_ENABLED=NO", "-DPLUGIN_CEGAR_ENABLED=NO"]

DEFAULT = "release64"
DEBUG = "debug64"
